kind: Service
apiVersion: v1
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  selector:
    app: webapi
  ports:
  - protocol: TCP
    port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: net7webapicontainer.azurecr.io/net7web-api:latest
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webapi
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        ports:
        - containerPort: 80